In [2]:
#np.linalg.solve 활용한 방법
import numpy as np
A = np.array([[2,3],[5,6]])
B = np.array([4,5])
C = np.linalg.solve(A,B)
print(C)

[-3.          3.33333333]


In [4]:
import numpy as np
A = np.array([[-2,-5,2],[1,3,0],[0,1,3]])
B = np.array([-3,4,6])
C = np.linalg.solve(A,B)
print(C)

[-5.  3.  1.]


In [5]:
import numpy as np
A = np.array([[2,3],[5,6]])
B = np.array([4,5])
C = np.linalg.inv(A)
D = np.dot(C,B)
print(D)

[-3.          3.33333333]


In [6]:
import numpy as np
A = np.array([[-2,-5,2],[1,3,0],[0,1,3]])
B = np.array([-3,4,6])
C = np.linalg.inv(A)
D = np.dot(C,B)
print(D)

[-5.  3.  1.]


In [9]:
import numpy.linalg as lin
a = np.array([[1,1], [2,1],[3,1]])

D = np.transpose(a)
B = np.dot(D,a)
C = lin.inv(B)
AP = np.matmul(C,D)
print(AP)

[[-0.5         0.          0.5       ]
 [ 1.33333333  0.33333333 -0.66666667]]


In [13]:
from numpy.linalg.linalg import transpose
import numpy.linalg as lin
a = np.array([[1,1,1,1],
             [8,4,2,1],
             [27,9,3,1],
             [64,16,4,1],
             [125,25,5,1],
             [216,36,6,1]])

b = np.array([2.1,3.5,4.2,3.1,4.4,6.8])

B = np.dot(D,a)
C = lin.inv(B)
D = transpose(a)

AP = np.matmul(C,D)
print("Pseudo Matrix : ", AP)
E = np.dot(AP,b)
print("Answer : ", E)

Pseudo Matrix :  [[-0.0462963   0.06481481  0.03703704 -0.03703704 -0.06481481  0.0462963 ]
 [ 0.57539683 -0.6984127  -0.46031746  0.31746032  0.66269841 -0.3968254 ]
 [-2.23544974  2.09391534  1.64550265 -0.64550265 -1.84391534  0.98544974]
 [ 2.66666667 -1.33333333 -1.33333333  0.33333333  1.33333333 -0.66666667]]
Answer :  [ 0.2        -1.96785714  6.13214286 -2.3       ]


In [17]:
from numpy.linalg.linalg import transpose
import numpy.linalg as lin
a = np.array([[1,-1,1],
              [-1,1,1],
              [1,1,-1],
              [1,1,1]])

D = transpose(a)
B = np.dot(D,a)
C = lin.inv(B)

AP = np.matmul(C,D)
print(AP)

[[ 0.25 -0.25  0.25  0.25]
 [-0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25  0.25]]
