In [22]:
import numpy as np

In [23]:
d_array = np.array([[2, 5], 
                    [1,3]])
print(d_array)

[[2 5]
 [1 3]]


In [24]:
d_array_det = np.linalg.det(d_array)

In [25]:
print(d_array_det)

1.0


In [26]:
d_array_inv = np.linalg.inv(d_array)

In [27]:
print(d_array_inv)

[[ 3. -5.]
 [-1.  2.]]


In [28]:
d_array = np.array([[2,5], [1,3]])
print(np.transpose(d_array))
print(d_array.transpose())
print(d_array.T)

[[2 1]
 [5 3]]
[[2 1]
 [5 3]]
[[2 1]
 [5 3]]


In [32]:
import numpy as np

In [33]:
x  = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
np.diag(x)


array([0, 4, 8])

In [41]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [42]:
b = np.arange(16).reshape(4, 4)

print(b)

np.trace(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30