In [24]:
import numpy as np

In [25]:
A = np.array([[0.0, 1.0, -3.0], [2.0, 3.0, -1.0], [4.0, 5.0, -2.0]])
B = np.array([[-5.0], [7.0], [10.0]])

In [26]:
import copy
def change(inp_list, inp1, inp2):
  tmp = copy.deepcopy(inp_list[inp1])
  inp_list[inp1] = inp_list[inp2]
  inp_list[inp2] = tmp
  result = inp_list
  return inp_list

In [30]:
rows_with_nonzero = 2
a = change(A, 0, rows_with_nonzero)
b = change(B, 0, rows_with_nonzero)
print(a)
print(b)

[[ 0.  1. -3.]
 [ 2.  3. -1.]
 [ 4.  5. -2.]]
[[-5.]
 [ 7.]
 [10.]]


In [31]:
def check_matrix(a,b):
  print(a)
  print('===============')
  print(b)

In [29]:
def find_rows_with_nonzero(AA,r,row_index):
r = 0
for c in range(len(row_index)):
  if AA[c][r] ! = 0.0:
    rows_with_nonzero = c
    pivot_number = AA[c][r]
    break
  
return rows_with_nonzero

IndentationError: ignored

In [32]:
row_index = list(range(len(A)))
print(row_index)
print(len(row_index))

[0, 1, 2]
3


In [33]:
col_index  = len(A[0])
print(A[0])
print(col_index)

[ 0.  1. -3.]
3


In [ ]:
def find_rows_with_nonzero(AA,r,row_index):
  r = 0
  for c in range(len(row_index)):
    if (AA[c][r] ! = 0.0):
        rows_with_nonzero = c
        pivot_number = AA[c][r]
        break
  
    return rows_with_nonzero

print(find_rows_with_nonzero(A,0,row_index))

In [ ]:
pivot_row = find_rows_with_nonzero(A, 0, row_index)
print(pivot_row[0])
pivot = A[pivot_row[0]][0]
print(pivot)

In [ ]:
pivot_row = np.zeros(col_index)
prin(pivot_row)