In [ ]:
import numpy as np

In [ ]:
x = np.arange(1,7).reshape(2,3)     #1,6까지 2행3열
y = np.array([[6,23],[-1,7],[8,9]]) # 2개의 배열 3개를 2행3열로 만들기

In [ ]:
B = np.dot(x,y)
print(B)

[[ 28  64]
 [ 67 181]]


In [ ]:
x_shape = np.shape(x)
print(x_shape)
y_shape = np.shape(y)
print(y_shape)
print(x_shape[0])

(2, 3)
(3, 2)
2


In [ ]:
def check_dot_matrix(xx,yy):
    x_shape = np.shape(xx)
    print(x_shape)
    y_shape = np.shape(yy)
    print(y_shape)
    print(x_shape[0])
    if x_shape[1] == y_shape[0] :
        print("행렬의 곱이 가능합니다.")
    else:
        print("행렬의 곱이 불가능합니다.")

In [ ]:
check_dot_matrix(y,x)

(3, 2)
(2, 3)
3
행렬의 곱이 가능합니다.


In [ ]:
C = np.linalg.inv(B)
print(C)

[[ 0.23205128 -0.08205128]
 [-0.08589744  0.03589744]]


In [ ]:
np.dot(B,C)

array([[ 1.00000000e+00, -4.44089210e-16],
       [ 2.63677968e-16,  1.00000000e+00]])

In [ ]:
d_array = np.array([[2,5], [1,3]])      
d_array_det = np.linalg.det(d_array)
print(d_array_det)

1.0


In [ ]:
import numpy.linalg as lin

d_array = np.array([[2,5],[1,3]])
d_array_det = lin.det(d_array)
print(d_array_det)

1.0


In [ ]:
d_array = np.array([[2,5],[1,3]])
print(d_array)
print(np.transpose(d_array))
print(d_array.transpose())
print(d_array.T)

[[2 5]
 [1 3]]
[[2 1]
 [5 3]]
[[2 1]
 [5 3]]
[[2 1]
 [5 3]]


In [72]:
def transpose_matrix(A):
    a_shape = np.shape(A)
    if a_shape[0] == a_shape[1]:
        B = np.zeros(a_shape) 
        print(B)
        for i in range(a_shape[0]):
            for j in range(i, a_shape[0]):
                print(i,j)
                B[i][j] = A[j][i]
                B[j][i] = A[i][j]

        return B
    else:
        print("정방행렬이 아닙니다.")

In [73]:
d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose_matrix(d_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0 0
0 1
0 2
1 1
1 2
2 2


array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])